version: '3'

services:
  financeiro:    
    image: ricardo1782/loja-java
    ports:
      - '8081:8081'
    links: 
      - db
  web-front:
    image: nginx
    ports:
      - '81:80'
    links:
      - financeiro
    volumes:
      - ./financas-front:/usr/share/nginx/html